site_name: Gaspare Mascolino
site_url: https://gaspare-mascolino.github.io/knowledge/

theme:
  name: null
  custom_dir: mkdocs-material
  language: en
  favicon: 'assets/images/triskele.png'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'assets/images/triskele.png'

extra_css:
  - stylesheets/style.css
  
markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html

docs_dir: docs/pages

plugins:
  - search
  - mermaid2

nav:
  - Computer Science: computer-science.md
  - English: english.md
  - Music: music.md