site_name: Gaspare Mascolino
site_url: https://gasparemascolino.com

theme:
  name: null
  custom_dir: pages/documents/mkdocs-material
  language: en
  favicon: 'images/triskele.png'
  feature:
    tabs: true
  palette:
    primary: 'white'
    accent: 'white'
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'images/triskele.png'
  
markdown_extensions:
  - admonition
  - footnotes

docs_dir: pages

nav:
  - Computer Science: computer-science.md
  - English: english.md
  - Music: music.md 